language : node_js 
node_js:
    - "6.8.0"
services :
    - postgresql
before_script :
    - npm install -g gulp-cli
    - npm install -g npm@5.3.0
    - npm install
    - psql -c 'create database base_fepol_test;' -U postgres

script : gulp test
